name: Docker Stretch

on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: debian-stretch
          file: debian-stretch/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:debian9,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:debian-9,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:debian-stretch,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:stretch,
