name: Docker Jessie

on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: debian-jessie
          file: debian-jessie/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:latest,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:debian8,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:debian-8,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:debian-jessie,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:jessie
