name: Docker Ubuntu 16.04

on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: ubuntu-16.04
          file: ubuntu-16.04/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:ubuntu16.04,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:ubuntu-16.04,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:ubuntu16,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:ubuntu-16,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:ubuntu-xenial-xerus,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:ubuntu-xenial,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:xenial-xerus,
                ${{ env.REGISTRY }}/${{ github.actor }}/handbrake:xenial,
